platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: latest

inputs:
- name: version
- name: git-docker-boshrelease

outputs:
- name: github-release
- name: git-docker-boshrelease-output
- name: notifications

params:
  AWS_ACCESS_KEY:
  AWS_SECRET_KEY:
  GIT_EMAIL:
  GIT_NAME:
  NOTIFICATION_OUT:
  RELEASE_ROOT:
  REPO_OUT:
  REPO_ROOT:
  VERSION_FROM:

run:
  path: git-docker-boshrelease/ci/scripts/ship-it
